server:
  port: 8080
  servlet:
    context-path: /students
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/interview
    username: admindb
    password: admin
  jpa:
    show-sql: true
    open-in-view: false
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL8Dialect
